javac Bar.java
javac @CoinSimViewer.list
java CoinSimViewer
javac Bar.java
javac @CoinSimViewer.list
java CoinSimViewer
javac Bar.java
javac @CoinSimViewer.list
java CoinSimViewer
javac Bar.java
javac Coin*.java
java CoinTossSimulatorTester
java CoinSimViewer
javac Bar.java
javac @CoinSimViewer.list
java CoinSimViewer
javac @CoinSimViewer.list
java CoinSimViewer
javac Bar.java
javac @CoinSimViewer.list
java CoinSimViewer
javac @CoinSimViewer.list
javac @CoinSimViewer.list
java CoinSimViewer
javac @CoinSimViewer.list
java CoinSimViewer
javac @CoinSimViewer.list
java CoinSimViewer
javac @CoinSimViewer.list
javac Coin*.java
javac Bar.java
java CoinTossSimulatorTester
java CoinTossSimulatorTester
java CoinTossSimulatorTester
java CoinSimViewer
javac Bar.java
javac Coin*.java
java CoinSimViewer
java CoinTossSimulatorTester
java CoinTossSimulatorTester
